### ISSUE TITLE
the method toLowerCase was called on null

### ISSUE THREAD

**Issue by wchoujaa** [bimsina/notes-app#3]
Bug: 

Add a note 
Add a note
Enter search bar
start writing

Console log: 

**Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/Choreographer( 8264): Skipped 48 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 8264): eglMakeCurrent: 0xeca05840: ver 3 0 (tinfo 0xd3290df0)
Syncing files to device Android SDK built for x86...
I/OpenGLRenderer( 8264): Davey! duration=1021ms; Flags=1, IntendedVsync=4917923176649, Vsync=4918723176617, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=4918739004630, AnimationStart=4918739096710, PerformTraversalsStart=4918739134630, DrawStart=4918754019840, SyncQueued=4918757296240, SyncStart=4918760140710, IssueDrawCommandsStart=4918761214970, SwapBuffers=4918860598040, FrameCompleted=4918947363890, DequeueBufferDuration=81773000, QueueBufferDuration=723000, 
D/EGL_emulation( 8264): eglMakeCurrent: 0xed1df1a0: ver 3 0 (tinfo 0xd4c451b0)
I/flutter ( 8264): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8264): The following assertion was thrown building:
I/flutter ( 8264): A non-null String must be provided to a Text widget.
I/flutter ( 8264): 'package:flutter/src/widgets/text.dart':
I/flutter ( 8264): Failed assertion: line 253 pos 10: 'data != null'
I/flutter ( 8264): 
I/flutter ( 8264): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8264): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8264): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8264):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8264): 
I/flutter ( 8264): When the exception was thrown, this was the stack:
I/flutter ( 8264): #2      new Text (package:flutter/src/widgets/text.dart:253:10)
I/flutter ( 8264): #3      NotesSearch.buildSuggestions.<anonymous closure> (package:notes_app/screens/search_note.dart:218:27)
I/flutter ( 8264): #4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
I/flutter ( 8264): #5      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
I/flutter ( 8264): #6      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
I/flutter ( 8264): #7      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
I/flutter ( 8264): #8      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
I/flutter ( 8264): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 8264): #10     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
I/flutter ( 8264): #11     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter ( 8264): #12     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter ( 8264): #13     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter ( 8264): #14     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter ( 8264): #15     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter ( 8264): #16     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
I/flutter ( 8264): #17     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
I/flutter ( 8264): #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
I/flutter ( 8264): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 8264): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 8264): #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 8264): #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 8264): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8264): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #48     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8264): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8264): #50     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8264): #51     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8264): #52     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8264): #53     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8264): #54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 8264): #55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 8264): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 8264): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8264): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 8264): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 8264): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 8264): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 8264): #65     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 8264): #66     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 8264): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 8264): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8264): Another exception was thrown: NoSuchMethodError: The method 'toLowerCase' was called on null.
I/flutter ( 8264): Another exception was thrown: NoSuchMethodError: The method 'toLowerCase' was called on null.
I/flutter ( 8264): Another exception was thrown: NoSuchMethodError: The method 'toLowerCase' was called on null.**

**Comment by bimsina** [comment]
I think adding ?.toLowerCase instead of .toLowerCase will fix this issue.
